/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "ExpGaussExp.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(ExpGaussExp) 

 ExpGaussExp::ExpGaussExp(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _mu,
                        RooAbsReal& _sigma,
                        RooAbsReal& _kL,
                        RooAbsReal& _kH) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   mu("mu","mu",this,_mu),
   sigma("sigma","sigma",this,_sigma),
   kL("kL","kL",this,_kL),
   kH("kH","kH",this,_kH)
 { 
 } 


 ExpGaussExp::ExpGaussExp(const ExpGaussExp& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   mu("mu",this,other.mu),
   sigma("sigma",this,other.sigma),
   kL("kL",this,other.kL),
   kH("kH",this,other.kH)
 { 
 } 



 Double_t ExpGaussExp::evaluate() const 
 { 
   Double_t t = (x-mu)/sigma;
   if (t <= -kL) {
      return TMath::Exp(kL*kL/2. + kL*t);
   } else if (t <= kH) {
      return TMath::Exp(-0.5*t*t);
   } else {
      return TMath::Exp(kH*kH/2. - kH*t);
   }
 } 



